### PR TITLE
support for neuron class annotations

### PR DESCRIPTION
**Pull request by jefferis**
Introduces a new function `class2ids()` that allows one to search for broad neuronal classes. It would be great to add more including

* KCs
* LHNs/TOONs etc
* CNs (including of different levels)

We also need to figure out a way to do the inverse (i.e. ids2class and possibly ids2type etc).

### CODE REVIEW

**Comment by jefferis** [comment]
@schlegelp could you suggest how we should identify the list of LHONs/CNs at the moment? Thanks!

**Comment by schlegelp** [comment]
"Strong" CNs are neurons that meet both of these criteria:
1. 5% of inputs or 50 synapses in total from PNs or is an MBON itself 
2. 5% of inputs or 50 synapses in total from MBONs or is a PN itself

Ideally the 5% of inputs would be counted per compartment (axon/dendrite).

For LHNs:
Either 5% of their pre- or post synapses in the LH. @alexanderbates used a connectivity approach to define LHNs based on inputs from uPNs.

In general: discard anything that's statusLabel `Orphan`, `Assign` or `Unimportant`

**Comment by jefferis** [comment]
Thanks @schlegelp! It would be great if you could provide exact code or queries and probably preferably a dump to a google sheet of the neurons thus identified (broken down by CN0/1 etc). The goal is to put you in charge of the definition and make it v quick and easy for others to retrieve the list of ids. Thanks!

**Comment by mmc46** [comment]
I've tested for PNs and RNs, and it seems to be working fine.

**Pull request merged**
